source 'https://rubygems.org'

# We test against other Rails versions, too. See `environments/`
rails_version = '~> 7.0.2'

gem 'activerecord', rails_version
gem 'actionpack',   rails_version

gem 'rspec', '~> 2.99'
gem 'mocha', '~> 0.9.8'

gem 'sqlite3', '~> 1.4.0'
gem 'mysql2', '~> 0.5.2', :group => :mysql
gem 'pg', '~> 1.2', :group => :pg
